Revert "bump @polkadot/*"
This reverts commit fa24255eb4095c35e6a656fac6295f80902fda7e.

which introduced this error:

```
src/api/api.service.ts:195:44 - error TS2339: Property 'isDoubleMap' does not exist on type 'StorageEntryTypeV14'.

195             ...(original.creator.meta.type.isDoubleMap ? arg : [arg]),
                                               ~~~~~~~~~~~

Found 1 error.
```